# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccFactorsUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Factors(object):
    def setupUi(self, Factors):
        Factors.setObjectName("Factors")
        Factors.resize(576, 485)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Factors.sizePolicy().hasHeightForWidth())
        Factors.setSizePolicy(sizePolicy)
        Factors.setMinimumSize(QtCore.QSize(300, 300))
        self.gridLayout = QtWidgets.QGridLayout(Factors)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.preampEdit = QtWidgets.QLineEdit(Factors)
        self.preampEdit.setObjectName("preampEdit")
        self.gridLayout.addWidget(self.preampEdit, 1, 3, 1, 1)
        self.cableButton = QtWidgets.QPushButton(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cableButton.sizePolicy().hasHeightForWidth())
        self.cableButton.setSizePolicy(sizePolicy)
        self.cableButton.setObjectName("cableButton")
        self.gridLayout.addWidget(self.cableButton, 2, 4, 1, 3, QtCore.Qt.AlignRight)
        self.cableEdit = QtWidgets.QLineEdit(Factors)
        self.cableEdit.setObjectName("cableEdit")
        self.gridLayout.addWidget(self.cableEdit, 2, 3, 1, 1)
        self.attenuatorLabel = QtWidgets.QLabel(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attenuatorLabel.sizePolicy().hasHeightForWidth())
        self.attenuatorLabel.setSizePolicy(sizePolicy)
        self.attenuatorLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.attenuatorLabel.setObjectName("attenuatorLabel")
        self.gridLayout.addWidget(self.attenuatorLabel, 3, 0, 1, 3)
        self.factorTable = QtWidgets.QTableView(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.factorTable.sizePolicy().hasHeightForWidth())
        self.factorTable.setSizePolicy(sizePolicy)
        self.factorTable.setLineWidth(1)
        self.factorTable.setShowGrid(True)
        self.factorTable.setObjectName("factorTable")
        self.gridLayout.addWidget(self.factorTable, 5, 0, 1, 7)
        self.preampButton = QtWidgets.QPushButton(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampButton.sizePolicy().hasHeightForWidth())
        self.preampButton.setSizePolicy(sizePolicy)
        self.preampButton.setObjectName("preampButton")
        self.gridLayout.addWidget(self.preampButton, 1, 5, 1, 2, QtCore.Qt.AlignRight)
        self.antennaLabel = QtWidgets.QLabel(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antennaLabel.sizePolicy().hasHeightForWidth())
        self.antennaLabel.setSizePolicy(sizePolicy)
        self.antennaLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.antennaLabel.setObjectName("antennaLabel")
        self.gridLayout.addWidget(self.antennaLabel, 0, 0, 1, 2)
        self.lisnEdit = QtWidgets.QLineEdit(Factors)
        self.lisnEdit.setObjectName("lisnEdit")
        self.gridLayout.addWidget(self.lisnEdit, 4, 3, 1, 1)
        self.antennaButton = QtWidgets.QPushButton(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antennaButton.sizePolicy().hasHeightForWidth())
        self.antennaButton.setSizePolicy(sizePolicy)
        self.antennaButton.setObjectName("antennaButton")
        self.gridLayout.addWidget(self.antennaButton, 0, 5, 1, 2, QtCore.Qt.AlignRight)
        self.preampLabel = QtWidgets.QLabel(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preampLabel.sizePolicy().hasHeightForWidth())
        self.preampLabel.setSizePolicy(sizePolicy)
        self.preampLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.preampLabel.setObjectName("preampLabel")
        self.gridLayout.addWidget(self.preampLabel, 1, 0, 1, 2)
        self.attenuatorButton = QtWidgets.QPushButton(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attenuatorButton.sizePolicy().hasHeightForWidth())
        self.attenuatorButton.setSizePolicy(sizePolicy)
        self.attenuatorButton.setObjectName("attenuatorButton")
        self.gridLayout.addWidget(self.attenuatorButton, 3, 6, 1, 1, QtCore.Qt.AlignRight)
        self.antennaEdit = QtWidgets.QLineEdit(Factors)
        self.antennaEdit.setObjectName("antennaEdit")
        self.gridLayout.addWidget(self.antennaEdit, 0, 3, 1, 1)
        self.attenuatorEdit = QtWidgets.QLineEdit(Factors)
        self.attenuatorEdit.setObjectName("attenuatorEdit")
        self.gridLayout.addWidget(self.attenuatorEdit, 3, 3, 1, 1)
        self.lisnButton = QtWidgets.QPushButton(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lisnButton.sizePolicy().hasHeightForWidth())
        self.lisnButton.setSizePolicy(sizePolicy)
        self.lisnButton.setObjectName("lisnButton")
        self.gridLayout.addWidget(self.lisnButton, 4, 6, 1, 1)
        self.cableLabel = QtWidgets.QLabel(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cableLabel.sizePolicy().hasHeightForWidth())
        self.cableLabel.setSizePolicy(sizePolicy)
        self.cableLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.cableLabel.setObjectName("cableLabel")
        self.gridLayout.addWidget(self.cableLabel, 2, 0, 1, 1)
        self.lisnLabel = QtWidgets.QLabel(Factors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lisnLabel.sizePolicy().hasHeightForWidth())
        self.lisnLabel.setSizePolicy(sizePolicy)
        self.lisnLabel.setMinimumSize(QtCore.QSize(75, 0))
        self.lisnLabel.setObjectName("lisnLabel")
        self.gridLayout.addWidget(self.lisnLabel, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Factors)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 3)

        self.retranslateUi(Factors)
        self.buttonBox.accepted.connect(Factors.accept)
        self.buttonBox.rejected.connect(Factors.reject)
        self.antennaButton.clicked.connect(Factors.browseAntennaSlot)
        self.preampButton.clicked.connect(Factors.browsePreampSlot)
        self.cableButton.clicked.connect(Factors.browseCableSlot)
        self.attenuatorButton.clicked.connect(Factors.browseAttenuatorSlot)
        self.lisnButton.clicked.connect(Factors.browseLisnSlot)
        self.antennaEdit.textChanged['QString'].connect(Factors.updateFactorsSlot)
        self.preampEdit.textChanged['QString'].connect(Factors.updateFactorsSlot)
        self.cableEdit.textChanged['QString'].connect(Factors.updateFactorsSlot)
        self.attenuatorEdit.textChanged['QString'].connect(Factors.updateFactorsSlot)
        self.lisnEdit.textChanged['QString'].connect(Factors.updateFactorsSlot)
        QtCore.QMetaObject.connectSlotsByName(Factors)
        Factors.setTabOrder(self.antennaButton, self.preampButton)
        Factors.setTabOrder(self.preampButton, self.cableButton)
        Factors.setTabOrder(self.cableButton, self.attenuatorButton)

    def retranslateUi(self, Factors):
        _translate = QtCore.QCoreApplication.translate
        Factors.setWindowTitle(_translate("Factors", "Factors"))
        self.cableButton.setText(_translate("Factors", "Browse"))
        self.attenuatorLabel.setText(_translate("Factors", "Attenuator/Limiter"))
        self.preampButton.setText(_translate("Factors", "Browse"))
        self.antennaLabel.setText(_translate("Factors", "Antenna"))
        self.antennaButton.setText(_translate("Factors", "Browse"))
        self.preampLabel.setText(_translate("Factors", "Preamp"))
        self.attenuatorButton.setText(_translate("Factors", "Browse"))
        self.lisnButton.setText(_translate("Factors", "Browse"))
        self.cableLabel.setText(_translate("Factors", "Cable"))
        self.lisnLabel.setText(_translate("Factors", "LISN"))
