# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccSettingsUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(654, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QtCore.QSize(415, 185))
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setGeometry(QtCore.QRect(510, 190, 131, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 631, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.settingsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.settingsLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsLayout.setObjectName("settingsLayout")
        self.fileSettingLayout = QtWidgets.QHBoxLayout()
        self.fileSettingLayout.setContentsMargins(0, 4, -1, 10)
        self.fileSettingLayout.setObjectName("fileSettingLayout")
        self.fileLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fileLabel.setObjectName("fileLabel")
        self.fileSettingLayout.addWidget(self.fileLabel)
        self.filepathEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.filepathEdit.setObjectName("filepathEdit")
        self.fileSettingLayout.addWidget(self.filepathEdit)
        self.browseFilesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.browseFilesButton.setObjectName("browseFilesButton")
        self.fileSettingLayout.addWidget(self.browseFilesButton)
        self.settingsLayout.addLayout(self.fileSettingLayout)
        self.groupsLayout = QtWidgets.QHBoxLayout()
        self.groupsLayout.setObjectName("groupsLayout")
        self.saGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saGroupBox.sizePolicy().hasHeightForWidth())
        self.saGroupBox.setSizePolicy(sizePolicy)
        self.saGroupBox.setObjectName("saGroupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.saGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.saForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.saForm.setContentsMargins(4, 15, 4, 4)
        self.saForm.setVerticalSpacing(15)
        self.saForm.setObjectName("saForm")
        self.saIPRadio = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.saIPRadio.setCheckable(True)
        self.saIPRadio.setAutoExclusive(True)
        self.saIPRadio.setObjectName("saIPRadio")
        self.saForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.saIPRadio)
        self.saIPEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.saIPEdit.setObjectName("saIPEdit")
        self.saForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.saIPEdit)
        self.saGPIBRadio = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.saGPIBRadio.setCheckable(True)
        self.saGPIBRadio.setObjectName("saGPIBRadio")
        self.saForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.saGPIBRadio)
        self.saGPIBSpin = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.saGPIBSpin.setObjectName("saGPIBSpin")
        self.saForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.saGPIBSpin)
        self.groupsLayout.addWidget(self.saGroupBox)
        self.ctrlGroupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctrlGroupBox.sizePolicy().hasHeightForWidth())
        self.ctrlGroupBox.setSizePolicy(sizePolicy)
        self.ctrlGroupBox.setObjectName("ctrlGroupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.ctrlGroupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 291, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.ctrlForm = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.ctrlForm.setContentsMargins(4, 15, 4, 4)
        self.ctrlForm.setVerticalSpacing(15)
        self.ctrlForm.setObjectName("ctrlForm")
        self.ctrlIPRadio = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.ctrlIPRadio.setCheckable(True)
        self.ctrlIPRadio.setObjectName("ctrlIPRadio")
        self.ctrlForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ctrlIPRadio)
        self.ctrlIPEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.ctrlIPEdit.setObjectName("ctrlIPEdit")
        self.ctrlForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ctrlIPEdit)
        self.ctrlGPIBRadio = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.ctrlGPIBRadio.setCheckable(True)
        self.ctrlGPIBRadio.setObjectName("ctrlGPIBRadio")
        self.ctrlForm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ctrlGPIBRadio)
        self.ctrlGPIBSpin = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.ctrlGPIBSpin.setObjectName("ctrlGPIBSpin")
        self.ctrlForm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ctrlGPIBSpin)
        self.groupsLayout.addWidget(self.ctrlGroupBox)
        self.settingsLayout.addLayout(self.groupsLayout)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        self.browseFilesButton.clicked.connect(Settings.browseSlot)
        self.saIPRadio.clicked.connect(Settings.saIPSelectSlot)
        self.saGPIBRadio.clicked.connect(Settings.saGPIBSelectSlot)
        self.ctrlIPRadio.clicked.connect(Settings.ctrlIPSelectSlot)
        self.ctrlGPIBRadio.clicked.connect(Settings.ctrlGPIBSelectSlot)
        self.saIPEdit.textChanged['QString'].connect(Settings.saIPSelectSlot)
        self.saGPIBSpin.valueChanged['int'].connect(Settings.saGPIBSelectSlot)
        self.ctrlIPEdit.textChanged['QString'].connect(Settings.ctrlIPSelectSlot)
        self.ctrlGPIBSpin.valueChanged['int'].connect(Settings.ctrlGPIBSelectSlot)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.fileLabel.setText(_translate("Settings", "Confidence Check File:"))
        self.browseFilesButton.setText(_translate("Settings", "Browse"))
        self.saGroupBox.setTitle(_translate("Settings", "Spectrum Analyzer"))
        self.saIPRadio.setText(_translate("Settings", "TCP/IP"))
        self.saGPIBRadio.setText(_translate("Settings", "GPIB"))
        self.ctrlGroupBox.setTitle(_translate("Settings", "Controller"))
        self.ctrlIPRadio.setText(_translate("Settings", "TCP/IP"))
        self.ctrlGPIBRadio.setText(_translate("Settings", "GPIB"))
